In [1]:
import pandas as pd
import numpy as np

In [2]:
def _transform_col( data ):
    vlr_orig, values, count = np.unique(data, return_inverse=True, return_counts=True)
    result = {}
    result['vlr-orig'] = list(vlr_orig)
    result['values'] = list(values)
    result['vlr-count'] = list(count)
    return result

In [3]:
def _transform_data(data, col_list):

    for colname in list(data.columns):
        if colname not in col_list: continue
        dados = data[ colname ]
        ret = _transform_col( dados )
        ret['colname'] = colname
        data.drop( columns=colname )
        data[ colname ] = ret['values']

    return data

In [4]:

def dataset_info(data):
    ###################
    data.info(verbose=True)
    print(data.describe())
    print('tipos:', data.dtypes)
    print('dimensoes:', data.ndim)
    print('linhas x colunas:', data.shape)
    ###################

In [5]:
def remover_dados_faltantes( df ):
    mascara = df.apply(lambda linha: linha.astype(str).str.contains(r'\?')).any(axis=1)

    # Retorna um DataFrame apenas com as linhas que **não** contêm '?'
    data = df[~mascara].copy()
    return data

In [6]:

def data_set( fname ):
    result = {}
    result['nome-arquivo'] = fname
    data = pd.read_csv(fname, skipinitialspace=True, skip_blank_lines=True)
    dataset_info(data)

    data = remover_dados_faltantes( data )
    # data.to_csv('adult--removido.csv', index=False)
    dataset_info(data)

    mystr = 'workclass, education,  marital-status, occupation,     relationship,   race,   sex,    native-country, class'
    process = [x.strip() for x in mystr.split(',')]
    data = _transform_data(data, process)

    ultima = data.columns[-1]
    classes = list(data[ultima])
    df = data.drop( columns=ultima )

    result['dados'] = df
    result['classes'] = classes

    return result

In [9]:
# Use the data_set function defined in the notebook, do not import from the package

FNAME = 'adult.csv'

if __name__ == '__main__':
    data = data_set(FNAME)
    for key, value in data.items():
        print(key)

    fname = FNAME.split('/')
    fname = fname[-1]
    print('fname -->', fname)
    # todo: salvar adult--dados.csv
    # todo: salvar adult--classes.csv  
    # ok: remover dados faltantes

    # todo: fazer o split do dataset: treino / teste

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   39             32560 non-null  int64
 1   State-gov      32560 non-null  object
 2   77516          32560 non-null  int64
 3   Bachelors      32560 non-null  object
 4   13             32560 non-null  int64
 5   Never-married  32560 non-null  object
 6   Adm-clerical   32560 non-null  object
 7   Not-in-family  32560 non-null  object
 8   White          32560 non-null  object
 9   Male           32560 non-null  object
 10  2174           32560 non-null  int64
 11  0              32560 non-null  int64
 12  40             32560 non-null  int64
 13  United-States  32560 non-null  object
 14  <=50K          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
                 39         77516            13          2174             0  \
count  32560.000000  3.256000e+04  32560.000000  32560.000000  32560.000000
mean      38.581634  1.897818e+05     10.080590   1077.615172     87.306511
std       13.640642  1.055498e+05      2.572709   7385.402999    402.966116
min       17.000000  1.228500e+04      1.000000      0.000000      0.000000
25%       28.000000  1.178315e+05      9.000000      0.000000      0.000000
50%       37.000000  1.783630e+05     10.000000      0.000000      0.000000
75%       48.000000  2.370545e+05     12.000000      0.000000      0.000000
max       90.000000  1.484705e+06     16.000000  99999.000000   4356.000000

                 40
count  32560.000000
mean      40.437469
std       12.347618
min        1.000000
25%       40.000000
50%       40.000000
75%       45.000000
max       99.000000
tipos: 39                int64
State-gov        object
77516             int64
Bachelors        object
13                int64
Never-married    object
Adm-clerical     object
Not-in-family    object
White            object
Male             object
2174              int64
0                 int64
40                int64
United-States    object
<=50K            object
dtype: object
dimensoes: 2
linhas x colunas: (32560, 15)
<class 'pandas.core.frame.DataFrame'>
Index: 30161 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   39             30161 non-null  int64
 1   State-gov      30161 non-null  object
 2   77516          30161 non-null  int64
 3   Bachelors      30161 non-null  object
 4   13             30161 non-null  int64
 5   Never-married  30161 non-null  object
 6   Adm-clerical   30161 non-null  object
 7   Not-in-family  30161 non-null  object
 8   White          30161 non-null  object
 9   Male           30161 non-null  object
 10  2174           30161 non-null  int64
 11  0              30161 non-null  int64
 12  40             30161 non-null  int64
 13  United-States  30161 non-null  object
 14  <=50K          30161 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
                 39         77516            13          2174             0  \
count  30161.000000  3.016100e+04  30161.000000  30161.000000  30161.000000
mean      38.437883  1.897976e+05     10.121216   1091.971984     88.375419
std       13.134882  1.056527e+05      2.549983   7406.466659    404.304753
min       17.000000  1.376900e+04      1.000000      0.000000      0.000000
25%       28.000000  1.176280e+05      9.000000      0.000000      0.000000
50%       37.000000  1.784290e+05     10.000000      0.000000      0.000000
75%       47.000000  2.376300e+05     13.000000      0.000000      0.000000
max       90.000000  1.484705e+06     16.000000  99999.000000   4356.000000

                 40
count  30161.000000
mean      40.931269
std       11.980182
min        1.000000
25%       40.000000
50%       40.000000
75%       45.000000
max       99.000000
tipos: 39                int64
State-gov        object
77516             int64
Bachelors        object
13                int64
Never-married    object
Adm-clerical     object
Not-in-family    object
White            object
Male             object
2174              int64
0                 int64
40                int64
United-States    object
<=50K            object
dtype: object
dimensoes: 2
linhas x colunas: (30161, 15)
nome-arquivo
dados
classes
fname --> adult.csv